### ISSUE TITLE
virus detected

### ISSUE THREAD

**Issue by sebas202** [GiacomoLaw/Keylogger#101]
**Describe the bug**
My windows pc detect it as an virus before it even is installed

**To Reproduce**
1. click install
2: error virus detected

**Expected behavior**
just install then run and then detect as a virus and run it anyway

**Desktop (please complete the following information):**
 - OS: windows 10 home insider preview
 - Version: Build 21292.rs_prerelease210108-1514

**Comment by quackduck** [comment]
This happens because Windows is confused by the structure of the executable. The code is open-source and easy to read. It does not contact any remote servers or anything. You can be sure this is not malicious.
