### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by aaannndddyyy** [GiacomoLaw/Keylogger#108]
**Describe the bug**
i opened the code in CodeBlocks and hit compile and got an error
C:\Users\Andy\Downloads\Keylogger-master\Keylogger-master\windows\klog_main.cpp|56|error: cannot convert 'LPCWSTR' {aka 'const wchar_t*'} to 'LPCSTR' {aka 'const char*'}|

**Expected behavior**
compiling

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by GiacomoLaw** [comment]
Try defining Unicode at the header:

`#define UNICODE 1`

**Comment by lenerdv2005** [comment]
which header? (i have the same problem)

**Comment by GiacomoLaw** [comment]
Right at the top
