### ISSUE TITLE
Codeblocks Error when compiling

### ISSUE THREAD

**Issue by azzlak** [GiacomoLaw/Keylogger#116]
hi,

as i wanted to compile it this error showed up:|93|error: cannot convert 'LPCWSTR' {aka 'const wchar_t*'} to 'LPCSTR' {aka 'const char*'}|

i cant read cpp. pls help

**Comment by n0sr3v** [comment]
Added a simple fix (google is your friend: https://stackoverflow.com/questions/11813767/cannot-convert-lpcwstr-aka-const-wchar-t-to-lpcstr-aka-const-char).
