### ISSUE TITLE
obfuscate and send log file?

### ISSUE THREAD

**Issue by vuslatx** [GiacomoLaw/Keylogger#121]
Actually, my two requests are independent of each other.

Is there a way to obfucate log file. Just swapping letters is enough. For example, "b" represents "w", so when i want to solve log file, i open text editor and replace "b" to "w". Thus, no one can see log file but me. 

Secondly, i want to send me log file with email/ftp or another way. What is the best and easiest way to do this for noob/newbie like me. How can i do this?

Note: from Windows 11

**Comment by GiacomoLaw** [comment]
Both parts are out of the scope of the project - not something I want to make publicly accessible and easy to use.
