### ISSUE TITLE
Invisible/Visible

### ISSUE THREAD

**Issue by Personary** [GiacomoLaw/Keylogger#122]
Hey, I'm having a little bit of difficulty understanding what the difference between visible and invisible are. They both keep the logger window opened, and when I close it when it is set to invisible it seems to stop the program. Is this intentional, or am I just stupid? I thought the invisible setting was going to make the window disappear, but it does not seem to do that. Any help would be greatly appreciated! Thank you, this truly is a great program anyways.

**Comment by GiacomoLaw** [comment]
Invisible should mean the window doesn't come up, and that when you start it no window comes up. Sounds like a bug

**Comment by GiacomoLaw** [comment]
Merged into #95

**Comment by mydarkthawts** [comment]
I added the `FreeConsole();` call after `ShowWindow(FindWindowA("ConsoleWindowClass", NULL), 0); // invisible window` which resolves this concern.
I submitted a [pull request](https://github.com/GiacomoLaw/Keylogger/pull/149) with the change. Hopefully it is accepted as a solution.
