### ISSUE TITLE
Information for the log file location

### ISSUE THREAD

**Issue by jack07Code** [GiacomoLaw/Keylogger#123]
What's the name of the log file and where it is?

**Comment by TheITkid** [comment]
I don't know. I have the same problem. Someone help please...?!

**Comment by bartoszluka** [comment]
It should be in the downloaded repo location under the name `keylogger.log` (for windows). But it depends on the platform

**Comment by GiacomoLaw** [comment]
Yep as bartoszluka said, should be under the repo if you are on Windows.

https://github.com/GiacomoLaw/Keylogger/blob/7e57f99025a40d86eb503035ae8529a68cd0c6d1/windows/klog_main.cpp#L198
