### ISSUE TITLE
Python package install error

### ISSUE THREAD

**Issue by MedCy1** [GiacomoLaw/Keylogger#125]
I have a weird issue
When I install another python module an error appears:
`WARNING: Error parsing requirements for keylogger: [Errno 2] No such file or directory: 'c:\\users\\username\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\keylogger-2.7.3.dist-info\\METADATA'`

When i want to uninstall keylogger i get these errors:
`WARNING: No metadata found in c:\users\username\appdata\local\programs\python\python39\lib\site-packages`

`ERROR: Cannot uninstall keylogger 2.7.3, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps keylogger==2.7.3'.`

And when I use what they say in the error I get the same error

**Comment by GiacomoLaw** [comment]
Did you install it via pip?
