### ISSUE TITLE
I can't compile on windows, i have this, any help to understand pls

### ISSUE THREAD

**Issue by Syrfa** [GiacomoLaw/Keylogger#129]
![image](https://user-images.githubusercontent.com/87822587/197787107-7a80a442-2e9b-4993-a793-ce7aa1df09c3.png)

**Comment by dXu23** [comment]
The error seems pretty straightforward actually. LPWSTR is a const pointer to a wchar_t, which stands for wide character. LPCSTR is a const pointer to character. The most obvious and naive fix is to go to the code block at klog_main.cpp at line 56 and change the type of a to LPCSTR.

**Comment by GiacomoLaw** [comment]
> The error seems pretty straightforward actually. LPWSTR is a const pointer to a wchar_t, which stands for wide character. LPCSTR is a const pointer to character. The most obvious and naive fix is to go to the code block at klog_main.cpp at line 56 and change the type of a to LPCSTR. Edit: Actually it might be on line 92 of klog_main.cpp in the windows folder.

Cheers
