### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by kalinochkind** [GiacomoLaw/Keylogger#13]

**Comment by cjwelborn** [comment]
Implemented for linux in PR #20. Awaiting review :wink:. I don't do windows, so I'll leave that for someone else. The linux version was only a few lines (`print` -> `print()`, and a small `bytes`/`str` issue).

**Comment by GiacomoLaw** [comment]
Implemented by @cjwelborn https://github.com/GiacomoLaw/Keylogger/pull/20#pullrequestreview-14723308
