### ISSUE TITLE
I am not getting any log in Ubuntu 22.04

### ISSUE THREAD

**Issue by nyck33** [GiacomoLaw/Keylogger#130]
**Describe the bug**

Not getting any log just Python commands.

**To Reproduce**
clone repo, follow readme instructions for linux, start typing in a test.txt file in the linux folder, type fg and ctrl-C to stop, check nohup.out and I see
```
Exception ignored in: <module 'threading' from '/home/nobu/anaconda3/envs/kafka/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/home/nobu/anaconda3/envs/kafka/lib/python3.9/threading.py", line 1477, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```
I typed in test.txt
```
I want to buy a nice coffee for myself.  
```

**Expected behavior**
It should have logged those keys for that sentence.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 22.04.01

**Additional context**
I did do a pip install keylogger in the same conda environment prior to cloning the repo and installing with `requirements.txt` so maybe it's interfering?

**Comment by Kapi-hub** [comment]
Hello @nyck23 .

The ouput of the keylogger is in a .log file. By listing the files in the cloned repository, you can see a "nohup.out" **and** a .log file. Open the .log file. 

!! Be aware of the fact that the .log file is created after an instance of the keylogger was started.

I hope this solves  the issue!

**Comment by JustSamAgain** [comment]
Hi!
I have the same problem using fedora39. (and I haven't had any previous keylogger installed - the fedora-install is fairly new)

The only output in the nohup.out file I get is (repeatedly):
```
Exception ignored in: <module 'threading' from '/usr/lib64/python3.12/threading.py'>
 Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1613, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

I searched everything for a .log file, in the whole cloned repo - there is none..maybe that changed during the last year..

I hope you have an idea what's the problem here and can help me out with that.

Have a great day/night!

**Comment by Kapi-hub** [comment]
Hi! @JustSamAgain 

I am the guy who replied previously, so I feel like I should leave a comment. 

Unfortunately, I am not familiar with the tool anymore, as I started to channel my attention towards other (personal) plans. I do not have an answer to your issue. I hope it will be solved by someone else.

Greetings,
Alex
