### ISSUE TITLE
Don`t working on another PC

### ISSUE THREAD

**Issue by xthr0** [GiacomoLaw/Keylogger#134]
After building the code in Visual Studio, I decided to try it out on another Windows 11 PC. But there were constantly DLL-related errors.

"Unable to continue code execution because the system has not detected urctbased.dll ; VCRUNTIME140D.dll ; VCRUNTIME140_1D.dll ; MSVCP140D.dll "

Okay, I moved the system folders to the missing files, but after that a new error occurred. 

"Application startup error (0xc000007b)"

**Comment by GiacomoLaw** [comment]
Reinstall visual studio runtimes.
