### ISSUE TITLE
Change default log file location

### ISSUE THREAD

**Issue by kalinochkind** [GiacomoLaw/Keylogger#14]
By default it tries to create the log file in some weird directory that doesn't exist on my PC. Maybe it should use home directory instead?

**Comment by GiacomoLaw** [comment]
Sorry, set it as my desktop. Feel free to change and submit a pull request. 😄

**Comment by GiacomoLaw** [comment]
https://github.com/GiacomoLaw/Keylogger/commit/8456911423f8a4eb3c586b1d74e7c419b737ac06

Best I could do with what I have 😞
