### ISSUE TITLE
Provide compiled package(s).

### ISSUE THREAD

**Issue by RokeJulianLockhart** [GiacomoLaw/Keylogger#146]
**Is your feature request related to a problem? Please describe.**
I don't want to have to `make` this, but https://github.com/GiacomoLaw/Keylogger/releases appears to solely contain source code.

**Describe the solution you'd like**
Submit to https://packaging.python.org/en/latest/tutorials/packaging-projects/#packaging-python-projects

**Describe alternatives you've considered**
Submit to individual distributions' package managers. This would be better, but would require more work (even if using something great like https://openbuildservice.org/).

**Comment by GiacomoLaw** [comment]
It's open source - compile it yourself. It won't ever go onto any package managers or be distributed in a compiled way.

**Comment by RokeJulianLockhart** [comment]
Why, @GiacomoLaw?

**Comment by GiacomoLaw** [comment]
Because it's for educational purposes. For people to see how it's built. If I were to package and distribute it, its distribution of malware.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/GiacomoLaw/Keylogger/issues/146#issuecomment-1803353730

Only if that's the intention, surely? For me, I just want to record what I've been typing in the day in order to have a log. (I also log everything sent to `tty0`, you see).

**Comment by GiacomoLaw** [comment]
It's easy enough to compile yourself. Releasing a compiled version would mean that anyone would be able to distribute and use it, which is not the intent.
