### ISSUE TITLE
a feature i wanna add

### ISSUE THREAD

**Issue by yo-aiv1** [GiacomoLaw/Keylogger#153]
Hi, i wanna ask if this feature will get accepted before i add it.
i wanna add args for the program instead of defining visibility...
so the user can pass args to the keylogger instead of editing the source code, also they will be default options in case the user didnt pass any args, and also cleaning the project and rewriting some comments in a better way while keeping the meaning, also an arg for the user if wanna add it to the startup folder so it'll run everytime the computer turns on.
I just wanted to ask before doing anything, because i wanna contribute to this project not to just fork and keep it for myself.
if you have any changes to those things i wanna do, please feel free to say it.

**Comment by mydarkthawts** [comment]
Hi @yo-aiv1 I was also working on this so we would all love to see your contributions! Would save me the trouble. Been a buy work week and not a chance to get back to the enhancements and cleanups.

**Comment by mydarkthawts** [comment]
What I currently have going is argc and argv checks and passing them through with if's to call functions vs having them done pragmatically. 
An if doesn't exist will just set default values. 

It works, just want to clean it up before submitting a pull.

**Comment by yo-aiv1** [comment]
@mydarkthawts hi, if you already finished it, no need for me to do it, just push yours
