### ISSUE TITLE
How to compile with visual studio 2022?

### ISSUE THREAD

**Issue by ghost** [GiacomoLaw/Keylogger#158]
hi, I would like to know how to compile and run this kl in visual studio 2022, I'm new to this, if you could explain it to me in detail I would appreciate it

**Comment by mydarkthawts** [comment]
@azuredrops https://github.com/GiacomoLaw/Keylogger/issues/80#issuecomment-1925503134

**Comment by ghost** [comment]
> @azuredrops [#80 (comment)](https://github.com/GiacomoLaw/Keylogger/issues/80#issuecomment-1925503134)

thank you

**Comment by mydarkthawts** [comment]
> > @azuredrops [#80 (comment)](https://github.com/GiacomoLaw/Keylogger/issues/80#issuecomment-1925503134)
> 
> thank you

No problem! Enjoy and good luck on your journey!
