### ISSUE TITLE
Windows: two identical files for "visible" and "invisible"

### ISSUE THREAD

**Issue by adotout** [GiacomoLaw/Keylogger#16]
Use a preprocessor directive https://msdn.microsoft.com/en-us/library/2a1b21sf.aspx . Then you can build with -DVISIBLE or -DINVISIBLE. You could create a simple makefile to build both the visible and invisible versions every time you build.

**Comment by GiacomoLaw** [comment]
Nice thinking! I'll add this sometime in the near future.

**Comment by GiacomoLaw** [comment]
https://github.com/GiacomoLaw/Keylogger/commit/5a71fce65971cea74c456d9aa011d8e77e7ba354

Added.
