### ISSUE TITLE
[Help] Coding noob, how do I compile into .exe?

### ISSUE THREAD

**Issue by thegrapeanator** [GiacomoLaw/Keylogger#19]
Help!

**Comment by GiacomoLaw** [comment]
Check this out!

http://www.wikihow.com/Compile-CPP-File-to-EXE

Hope that helps out!

**Comment by GiacomoLaw** [comment]
@thegrapeanator everything good?

**Comment by GiacomoLaw** [comment]
Cool, glad it helped you!
