### ISSUE TITLE
MAC Installation

### ISSUE THREAD

**Issue by Gilgalidd** [GiacomoLaw/Keylogger#22]
Hello,
 
I cannot install the mac version due to the lack of file, the make cannot run because the makefile doesn't exist.

Is the Mac version working?

Thanks,

**Comment by GiacomoLaw** [comment]
I'll see if I can fix it.

**Comment by GiacomoLaw** [comment]
Fixed it:

https://github.com/GiacomoLaw/Keylogger/commit/6e7cafd2607aa7d0311629bfe152fa2c7eaf5717

Let me know if it works

**Comment by Gilgalidd** [comment]
it works, Thanks.

**Comment by GiacomoLaw** [comment]
Okay, great!
