### ISSUE TITLE
windows-keys are logged only for the user who run the keylogger

### ISSUE THREAD

**Issue by itaym120** [GiacomoLaw/Keylogger#31]
I tried using it as the domain administrator but it logged only the keys i pressed. not the keys of the user who is actually logged in.
Any idea how to change it to get all the pressed keys of the computer its running at?

Great project nonetheless :+1:

**Comment by GiacomoLaw** [comment]
Where did you install it?

**Comment by itaym120** [comment]
windows 7.
i tried running it as the user "sadmin"  and even as "system" but it always get only the keylogs of the user who runned it and not the logged in user

**Comment by GiacomoLaw** [comment]
It only installs for the user that installs it I believe. I'm not sure how to install it for all users.

This may help: https://stackoverflow.com/questions/23632806/how-can-i-install-an-exe-file-for-all-user-accounts-on-a-computer
