### ISSUE TITLE
#include<stdio.h> needed due to fprintf function

### ISSUE THREAD

**Issue by bit4woo** [GiacomoLaw/Keylogger#34]
It seems that  the klog_main.cpp need to include <stdio.h> head file.   because the fprintf  function.

I used  codeblocks IDE to compile the source code.

![image](https://user-images.githubusercontent.com/8793481/28253927-d22b2cde-6ada-11e7-9e61-bf4a45ce201b.png)

**Comment by GiacomoLaw** [comment]
Included 🙂
