### ISSUE TITLE
Need to provide attribution to Mac keylogger code

### ISSUE THREAD

**Issue by KrbAlmryde** [GiacomoLaw/Keylogger#39]
Its pretty clear the Mac distribution code was taken verbatim from @caseyscarborough 's work found here: `https://github.com/caseyscarborough/keylogger` 

yet, there is no attribution in the readme.  If you're going to distribute someone else's work, at least give them credit where its due.

**Comment by GiacomoLaw** [comment]
There is, at the bottom under the uninstall section. It's also said on the website 🙂

**Comment by KrbAlmryde** [comment]
So it does! I only see it on the main page and not under the Mac sections itself. You ought to provide a direct link to the original Repo. Thanks for pointing it out to me.

**Comment by GiacomoLaw** [comment]
Will do, thanks!
