### ISSUE TITLE
Please give credit to caseyscarborough/keylogger

### ISSUE THREAD

**Issue by luolong** [GiacomoLaw/Keylogger#40]
You've used code from [caseyscarborough/keylogger](https://github.com/caseyscarborough/keylogger) for Mac keylogger almost verbatim, only ripping out comments in code and changing some of the README.

Please at least give some credit to the original author...

**Comment by GiacomoLaw** [comment]
See this: https://github.com/GiacomoLaw/Keylogger/issues/39

I've given credits in the readme 🙂

**Comment by luolong** [comment]
Great! The attribution was not very visible, so I submitted a pull request, making it stand out a bit more and also adding a link to the original repo
