### ISSUE TITLE
Error LNK2019, LNK1120 in visual studio 2107 - windows 10  64-bit

### ISSUE THREAD

**Issue by erevos99** [GiacomoLaw/Keylogger#45]
I tried compiling with VS 2017 and I always have these errors. I am noobie. Does anyone knows what to do?

![error](https://user-images.githubusercontent.com/37023365/37062418-0e8b9cce-219f-11e8-943f-f3124e8f32eb.gif)

**Comment by GiacomoLaw** [comment]
Does it still compile and work fine?

**Comment by erevos99** [comment]
No, I did not find any solution.
