### ISSUE TITLE
klog_main.cpp:1:10: fatal error: Windows.h:

### ISSUE THREAD

**Issue by dufywihi** [GiacomoLaw/Keylogger#46]
@GiacomoLaw Having trouble compiling. Any ideas? What's `Windows.h`?

	$ lsb_release -a

	No LSB modules are available.
	Distributor ID:	Kali
	Description:	Kali GNU/Linux Rolling
	Release:	kali-rolling
	Codename:	kali-rolling

	$ g++ klog_main.cpp 

	klog_main.cpp:1:10: fatal error: Windows.h: No such file or directory
	 #include <Windows.h>
		  ^~~~~~~~~~~
	compilation terminated.

	$ make klog_main

	g++     klog_main.cpp   -o klog_main
	klog_main.cpp:1:10: fatal error: Windows.h: No such file or directory
	 #include <Windows.h>
		  ^~~~~~~~~~~
	compilation terminated.
	<builtin>: recipe for target 'klog_main' failed
	make: *** [klog_main] Error 1

**Comment by GiacomoLaw** [comment]
You are using the Windows version, but you are on Linux.

Use the Linux version instead: https://github.com/GiacomoLaw/Keylogger/tree/master/linux

Thanks for using!

**Comment by Julian-of-Aland** [comment]
I'm having the same problem but I'm on windows
