### ISSUE TITLE
Alphanumeric keystrokes doesn't work in MAC

### ISSUE THREAD

**Issue by christus02** [GiacomoLaw/Keylogger#47]
In MacBook (Late 2013) model, the log file shows only the special keys like CTRL, Shift, etc.
It does not log or not even detects the other alphanumeric keys.

**Comment by moliata** [comment]
Mac Keyloggers on newer version of macOS only works when is running with root: do `sudo ./keylogger`

**Comment by GiacomoLaw** [comment]
Thanks for resolving the issue!
