### ISSUE TITLE
Not working in Centos 7 min install ( without GUI)

### ISSUE THREAD

**Issue by zhenqidong** [GiacomoLaw/Keylogger#49]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "pyxhook.py", line 113, in __init__
>     self.local_dpy = display.Display()
>   File "/usr/lib/python2.7/site-packages/Xlib/display.py", line 89, in __init__
>     self.display = _BaseDisplay(display)
>   File "/usr/lib/python2.7/site-packages/Xlib/display.py", line 71, in __init__
>     protocol_display.Display.__init__(self, *args, **keys)
>   File "/usr/lib/python2.7/site-packages/Xlib/protocol/display.py", line 85, in __init__
>     name, protocol, host, displayno, screenno = connect.get_display(display)
>   File "/usr/lib/python2.7/site-packages/Xlib/support/connect.py", line 73, in get_display
>     return mod.get_display(display)
>   File "/usr/lib/python2.7/site-packages/Xlib/support/unix_connect.py", line 61, in get_display
>     raise error.DisplayNameError(display)
> Xlib.error.DisplayNameError: Bad display name ""

**Comment by GiacomoLaw** [comment]
Won’t work in min installs. Closing for now.
