### ISSUE TITLE
Why the double spacing?

### ISSUE THREAD

**Issue by jasonhamilton** [GiacomoLaw/Keylogger#5]

**Comment by GiacomoLaw** [comment]
Could you expand?

**Comment by jasonhamilton** [comment]
Under the Linux folder, the Python files have 2 spaces for each line of code.

**Comment by GiacomoLaw** [comment]
If its on this file: https://github.com/GiacomoLaw/Keylogger/blob/master/linux/pyxhook.py

Its pyxhook -- an extension to emulate some of the PyHook library on linux. I don't actually own or make that, if you check out the text at the top. 😉

**Comment by GiacomoLaw** [comment]
I'll close this, but feel free to ask any more questions! 😄
