### ISSUE TITLE
Visual Studio 2015 doesn't compile with standard setup.

### ISSUE THREAD

**Issue by YounesN** [GiacomoLaw/Keylogger#52]
I tried to compile the code on:

- Visual Studio Enterprise 2015 version 14.0.24720.00 Update 1
- Windows 10

I get the following errors:
`Error	C4996	'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	DataProtection	c:\Users\yneja\Desktop\Keylogger\windows\klog_main.cpp	79

Error	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	DataProtection	c:\Users\yneja\Desktop\Keylogger\windows\klog_main.cpp	69	

Error	C4996	'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	DataProtection	c:\Users\yneja\Desktop\Keylogger\windows\klog_main.cpp	83`

I got around it by _CRT_SECURE_NO_WARNINGS, but maybe they should be switched to safer versions.

**Comment by YounesN** [comment]
- OUTPUT_FILE = fopen(file, "a+");
    + fopen_s(&OUTPUT_FILE, file, "a+");

    - time_t t = time(NULL);
    - struct tm *tm = localtime(&t);
    - char s[64];
    - strftime(s, sizeof(s), "%c", tm);
    + time_t t = time(NULL);
    + struct tm tm;
    + localtime_s(&tm, &t);
    + char s[64];
    + strftime(s, sizeof(s), "%c", &tm);

    - strcpy(lastwindow, window_title);
    + strcpy_s(lastwindow, window_title);

**Comment by GiacomoLaw** [comment]
The issue with specifying a buffer size is that a user may miss some keystrokes if that is done.

Nothing will be harmful to your computer, however you can always edit your personal code if you would like. 😄
