### ISSUE TITLE
Can someone please upload a compiled EXE?

### ISSUE THREAD

**Issue by Benji-Collins** [GiacomoLaw/Keylogger#53]
I've followed about 7 tutorials on how to compile C++ programs in multiple different ways but nothing works. Everything is an error. Please can someone just send me the .exe. Preferably one build in invisible mode. I honestly don't even care if it has malware in it because I didn't build it myself.

**Comment by GiacomoLaw** [comment]
Sorry, but part of the reason that no .exe is supplied is to prevent it being used maliciously.

**Comment by Benji-Collins** [comment]
lmao
