### ISSUE TITLE
Keylogger does not run correctly when started from Task Scheduler or as a Service (Windows)

### ISSUE THREAD

**Issue by DerHeimataerde** [GiacomoLaw/Keylogger#56]
The program shows it is running in task manager, but it does not create a key log file when launched as a Task or service (using NSSM for the latter).

**Comment by GiacomoLaw** [comment]
Have you launched it manually before to create the log?

**Comment by DerHeimataerde** [comment]
Yes, it works just fine manually. To update, it also does not work if
placed in the user startup folder nor the common startup folder

**Comment by NathanJRollins** [comment]
The program stores the log file in the current working directory.  This is something like system32, sysWOW64, or %userprofile% if you let Task Scheduler launch the program.  Best solution (imo) is to specify the working directory (the directory with the program .exe) within Task Scheduler - and it will respect it, as though you just double-clicked the program to launch it at its location.

Modify the task -> Actions -> Edit -> "Start in (optional):"
Set this to the program's directory's path.  No quotation marks.  Spaces are allowed.
(:
