### ISSUE TITLE
Remove Linux PyPi packaging files

### ISSUE THREAD

**Issue by GiacomoLaw** [GiacomoLaw/Keylogger#70]
I was dumb and accidentally committed them. Need to remove them but don’t have experience with PyPi so don’t want to delete something important. 

Also, if someone would be able to manage the pip version that would be great. Haven’t done much packaging so help would be greatly appreciated.

**Comment by GiacomoLaw** [comment]
See #77.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/GiacomoLaw/Keylogger/issues/70#issuecomment-474601751

@GiacomoLaw, https://github.com/GiacomoLaw/Keylogger/issues/77 has been deleted.

**Comment by GiacomoLaw** [comment]
#141 replaces it, thanks
