### ISSUE TITLE
libstdc++-6.dll issue

### ISSUE THREAD

**Issue by Th3-A6add0n** [GiacomoLaw/Keylogger#71]
I compiled on Linux system using mingw64 g++.
compilation was successful but on testing got an error 
PFA
![annotation](https://user-images.githubusercontent.com/34588916/52080366-962ba480-25bd-11e9-9c84-638ad523ba4e.png)

**Comment by GiacomoLaw** [comment]
Does this help?

https://stackoverflow.com/questions/6404636/libstdc-6-dll-not-found
