### ISSUE TITLE
can I record other computer activity with this keylogger ?

### ISSUE THREAD

**Issue by kyzrsze1** [GiacomoLaw/Keylogger#72]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GiacomoLaw** [comment]
Only if you have the permission of the owner of that computer.

**Comment by GiacomoLaw** [comment]
Locking this because I do not provide support on install, or how to put it on someone else's computer without permission as that could be breaching laws.
