### ISSUE TITLE
MAPVK_VK_TO_CHAR was not declared in this scope

### ISSUE THREAD

**Issue by mazmazigh** [GiacomoLaw/Keylogger#78]
**Describe the bug**
I just copied and pasted the code.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Using Code Blocks with mingw compiler

**Comment by sandman4812av** [comment]
same issue :( and how resolve ??

**Comment by GiacomoLaw** [comment]
Seems to be an issue with `windows.h` header, can you verify that you have it installed?

**Comment by GiacomoLaw** [comment]
Closing this as no update, so I presume it is fixed.

**Comment by sandman4812av** [comment]
![image](https://user-images.githubusercontent.com/29623610/55396776-bb08ad80-5555-11e9-85b2-abc4e79dcb3f.png)

**Comment by GiacomoLaw** [comment]
Try including `#include "pch.h"` in the header of the file.

Thanks

**Comment by IsraelSuen** [comment]
GiacomoLaw,I think i was fucked by u,u just a kid who know nothing about code,cause ur repo`s issue haven`t fix the problem of ur code for this entire year,no doubt ur code was total shit on windows,kinda waste time on ur project.
