### ISSUE TITLE
How do you turn it off when invisible?

### ISSUE THREAD

**Issue by issuewithstuff** [GiacomoLaw/Keylogger#79]
I am using the windows version where it is invisible. However, when invisible, how do you end the process? I cannot find it in task manager.

**Comment by GiacomoLaw** [comment]
Hi there, it will be in task manager. Please check in the details tab.

![image](https://user-images.githubusercontent.com/9038673/55192088-9f8b5480-519b-11e9-82f1-9f276f54b714.png)

Thanks
