### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sh1va73** [GiacomoLaw/Keylogger#83]
I am on latest version of Kali and did pip install keylogger.
Then I get this error:

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-SzFCq9/keylogger/setup.py'"'"'; __file__='"'"'/tmp/pip-install-SzFCq9/keylogger/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-SzFCq9/keylogger/pip-egg-info
         cwd: /tmp/pip-install-SzFCq9/keylogger/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-SzFCq9/keylogger/setup.py", line 24, in <module>
        long_description="\n\n".join([open("README.md").read(), open("CHANGES.md").read()]),
      File "/usr/lib/python2.7/codecs.py", line 898, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'CHANGES.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by GiacomoLaw** [comment]
Try installing from the linux directory on this repo - pip is a bit broken for this repo. Or create a `changes.md` file.

**Comment by sh1va73** [comment]
I tried again but still no successful install.
When I run the command I get:
Traceback (most recent call last):
  File "keylogger.py", line 5, in <module>
    from keylogger import pyxhook
  File "/opt/Keylogger/linux/keylogger/keylogger.py", line 5, in <module>
    from keylogger import pyxhook
ImportError: cannot import name pyxhook

**Comment by GiacomoLaw** [comment]
Try running `pip install pyxhook`, and then install. Hope this works :D

**Comment by sh1va73** [comment]
pyxhook is already installed, still getting this error.

**Comment by ChillerDragon** [comment]
@sh1va73 is pyxhook installed in the python version you used to run the logger? I confused python2 and python3 dependencys when installing it. I recommend going with python3 nowerdays:

```
python3 -m pip install pyxhook
python3 keylogger.py
```

**Comment by sh1va73** [comment]
Thanks for the suggestion but it did not work. I'm giving up on this one as I never got it installed properly.

**Comment by GiacomoLaw** [comment]
This isn't an issue with the keylogger, but with your setup. Apologies that you couldn't get it working.

**Comment by willnaoosmith** [comment]
Same here

```
 pip install keylogger
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting keylogger
  Using cached keylogger-2.7.3.tar.gz (6.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-VONDNs/keylogger/setup.py'"'"'; __file__='"'"'/tmp/pip-install-VONDNs/keylogger/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-WERnzW
         cwd: /tmp/pip-install-VONDNs/keylogger/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-VONDNs/keylogger/setup.py", line 24, in <module>
        long_description="\n\n".join([open("README.md").read(), open("CHANGES.md").read()]),
      File "/usr/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'CHANGES.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

@sh1va73 did you find any solution to this?

**Comment by GiacomoLaw** [comment]
I haven't updated the pip repo in ages, I would just suggest installing it from here, not via pip.
