### ISSUE TITLE
Error [Mac]

### ISSUE THREAD

**Issue by victorlsn** [GiacomoLaw/Keylogger#92]
I keep getting this error:
ERROR: Unable to create event tap.

**Comment by ChillerDragon** [comment]
Could you maybe provide some information like macOS version or what compiler you used?

**Comment by Quotz** [comment]
I am getting the same, not sure why

**Comment by Quotz** [comment]
Solved it. Go to Settings -> Security & Privacy -> Accessibility and tick Terminal. Now run the command again

**Comment by GiacomoLaw** [comment]
Thanks for posting a fix!

**Comment by jjant** [comment]
I still get this error even with accessibility enabled for my terminal.

**Comment by jjant** [comment]
Interestingly, I tried running it from the builtin Terminal app and it worked (both have accessibility enabled).
