### ISSUE TITLE
"Invisible" Window feature not working (FindWindowA returns null?)

### ISSUE THREAD

**Issue by SimonKaluza** [GiacomoLaw/Keylogger#95]
**Describe the bug**
Setting the "invisible" macro does not correctly hide the console window.  i.e. the `ShowWindow(FindWindowA("ConsoleWindowClass", NULL), 0)` [call on line 161 of klog_main.cpp](https://github.com/GiacomoLaw/Keylogger/blob/master/windows/klog_main.cpp#L161) doesn't seem to have any effect.

**To Reproduce**
1. Create a new VS 2019 command-line CPP project
2. Paste the entire code of klog_main.cpp
3. Change `#define visible` to `#define invisible`
4. Command-line window showing Keylogger still remains open after compiling/running successfully.

**Expected behavior**
We expect the command-line window to be hidden, but it seems the call to `FindWindowA("ConsoleWindowClass", NULL)` returns null, which means the subsequent call to ShowWindow has no effect.

**Comment by mfrank37** [comment]
There exist [HWND WINAPI GetConsoleWindow(void);](https://learn.microsoft.com/en-us/windows/console/getconsolewindow) to get the console window of the keylogger, it works.

**Comment by mydarkthawts** [comment]
I added the `FreeConsole();` call after `ShowWindow(FindWindowA("ConsoleWindowClass", NULL), 0); // invisible` window which resolves this concern.
I submitted a pull request with the change. Hopefully it is accepted as a solution.

**Comment by GiacomoLaw** [comment]
Fixed in e931864230ae37b49b036634cb4843f0a1f4fa3e
