### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jmoney24244** [GiacomoLaw/Keylogger#98]
root💀DESKTOP-N1S5Q22)-[/mnt/c/Users/Mona moore/Keylogger/mac]
└─# make && make install
gcc keylogger.c -framework ApplicationServices -framework Carbon -o keylogger
gcc: error: ApplicationServices: No such file or directory
gcc: error: Carbon: No such file or directory
gcc: error: unrecognized command-line option ‘-framework’
gcc: error: unrecognized command-line option ‘-framework’
make: *** [Makefile:9: all] Error 1

 i dont know what it is

**Comment by GiacomoLaw** [comment]
See if following this fixes: https://stackoverflow.com/a/12919082/6752824
